packages:
  - packages/*
catalog:
  del-cli: ^6.0.0
  lerna: ^8.2.1
  typescript: ^5.8.3
  payload-is: ^0.4.0
  glob: ^11.0.2
  rollup: ^4.41.1
  ts-morph: ^26.0.0
  esbuild: 0.25.4
  browserslist-to-esbuild: ^2.1.1
  vitest: ^3.2.2
  "@babel/core": ^7.27.4
  "@babel/plugin-transform-runtime": ^7.27.4
  "@babel/preset-env": ^7.27.2
  "@babel/preset-typescript": ^7.27.1
  "@types/node": ^22.13.11
  "@types/babel__core": ^7.20.5
  "@swc/core": ^1.11.31
  "@rollup/pluginutils": ^5.1.4
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-commonjs": ^28.0.3
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
