packages:
  - packages/*
catalog:
  "@types/node": ^22.13.11
  "@tsconfig/node-ts": ^23.6.1
  "@tsconfig/node20": ^20.1.5
  del-cli: ^6.0.0
  lerna: ^8.2.1
  typescript: ^5.8.3
  payload-is: ^0.3.3
  glob: ^11.0.2
  rollup: ^4.41.1
  "@babel/core": ^7.27.4
  "@types/babel__core": ^7.20.5
  "@babel/plugin-transform-runtime": ^7.27.4
  "@babel/preset-env": ^7.27.2
  "@babel/preset-typescript": ^7.27.1
  "@rollup/plugin-babel": ^6.0.4
  ts-morph: ^26.0.0
  esbuild: 0.25.4
  browserslist-to-esbuild: ^2.1.1
  "@swc/core": ^1.11.31
  "@rollup/plugin-swc": ^0.4.0
  "@rollup/pluginutils": ^5.1.4
  vitest: ^3.2.2
  smob: ^1.5.0
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
